spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogs?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.athut: debug
server:
  port: 8081